site_name: spectralmatch
site_url: https://spectralmatch.github.io/spectralmatch/
repo_url: https://github.com/spectralmatch/spectralmatch

theme:
    name: material
    palette:
        primary: green
        accent: deep-orange
    logo: images/icon.png
    features:
        - navigation.instant
        - search.highlight
    custom_dir: docs/overrides

plugins:
    - search
    - mkdocstrings:
        handlers:
          python:
            options:
                show_root_toc_entry: false
    - git-revision-date
    - mkdocs-jupyter:
        include_source: true
        execute: false
        ignore_h1_titles: true

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true
          toc_depth: 2

nav:
    - Home: index.md
    - Installation: installation.md
    - Changelog: https://github.com/spectralmatch/spectralmatch/releases
    - Report Issues: https://github.com/spectralmatch/spectralmatch/issues
    - Contributing Guide: contributing.md
    - File Formats and Input Requirements: formats_and_requirements.md
    - Examples:
        - "Match: Global to Local": examples/example_global_to_local.py
        - Create Cloud Mask: examples/mask_cloud.py
        - Create Vegetation Mask: examples/mask_ndvi.py
        - Calculate Statistics for Figures: examples/calculate_statistics.py
        - Benchmark Mulithreading: examples/benchmark.py
    - API Reference:
        - Matching Algorithms: api/match.md
        - Create Mask and Pseudo-Invariant Features: api/mask.md
        - Creating Statistical Figures: api/statistics.md
        - Data Handlers for IO: api/handlers.md

extra_css:
    - docs/overrides/custom.css

extra_javascript:
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js