site_name: spectralmatch
site_url: https://spectralmatch.github.io/spectralmatch/
repo_url: https://github.com/spectralmatch/spectralmatch

theme:
    name: material
    palette:
        primary: green
        accent: deep-orange
    logo: images/icon.png
    features:
        - navigation.instant
        - search.highlight
    custom_dir: overrides

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: true
        execute: false
        ignore_h1_titles: true

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true
          toc_depth: 2

nav:
    - Home: index.md
    - Installation: installation.md
    - Changelog: https://github.com/spectralmatch/spectralmatch/releases
    - Report Issues: https://github.com/spectralmatch/spectralmatch/issues
    - Examples:
        - Global to Local: examples/example_global_to_local.py
        - Benchmark Mulithreading: examples/benchmark.py
        - Calculate Statistics: examples/calculate_statistics.py
        - Cloud Masking: examples/mask_cloud.py
        - Vegetation Masking: example/mask_ndvi.py
    - API Reference:
        - Matching Algorithms: api/match.md
        - Masking: api/mask.md
        - Statistics: api/statistics.md
        - Handlers: api/handlers.md

extra_css:
    - docs/overrides/custom.css

extra_javascript:
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js