site_name: spectralmatch
site_url: https://spectralmatch.github.io/spectralmatch/
repo_url: https://github.com/spectralmatch/spectralmatch

theme:
    name: material
    palette:
        primary: green
        accent: deep-orange
    logo: images/icon.png
    features:
        - navigation.instant
        - search.highlight
    custom_dir: docs/overrides

plugins:
    - search
    - mkdocstrings:
        handlers:
          python:
            options:
                show_root_toc_entry: false
    - git-revision-date-localized:
        enabled: true
        exclude:
            - llm_prompt.md
    - mkdocs-jupyter:
        include_source: true
        execute: false
        ignore_h1_titles: true
    - gen-files:
          scripts:
              - docs/create_llm_prompt.py
              - docs/create_cli.py

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true
          toc_depth: 2

nav:
    - Home: index.md
    - Installation: installation.md
    - RRN Methods: rrn_methods.md
    - Changelog: https://github.com/spectralmatch/spectralmatch/releases
    - Report Issues: https://github.com/spectralmatch/spectralmatch/issues
    - Contributing Guide: contributing.md
    - File Formats and Input Requirements: formats_and_requirements.md
    - Examples:
        - WorldView Mosaic: examples/example_worldview_mosaic.py
        - Landsat Time Series: examples/example_landsat_time_series.py
        - Benchmark Multithreading: examples/benchmark.py
    - API Reference:
        - Data Handlers: api/handlers.md
        - Create Masks: api/mask.md
        - Matching Algorithms: api/match.md
        - Create Seamlines: api/seamline.md
        - Utilities: api/utils.md
        - Statistical Figures: api/statistics.md
    - Command Line Interface: cli.md

extra_css:
    - docs/overrides/custom.css

extra_javascript:
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js