name: Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          channels: conda-forge
          conda-remove-defaults: true

      - name: Create Conda environment for docs
        run: |
          conda create --name docs_env python=3.12 "gdal=3.10.2" "proj>=9.3" --override-channels -c conda-forge -v

      - name: Activate environment and install docs dependencies
        shell: bash -l {0}
        run: |
          conda activate docs_env
          pip install -e ".[docs]"

      - name: Build docs
        shell: bash -l {0}
        run: |
          conda activate docs_env
          make docs-build

      - name: Deploy docs
        shell: bash -l {0}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate docs_env
      
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          make docs-deploy