name: Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Install Python dependencies
        run: pip install ".[docs]"

      - name: Build docs
        run: make docs-build

      - name: Deploy docs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make docs-deploy