name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: "Full version tag to create release for (e.g. 'v1.2.3')"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out the repository at the tag
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ github.event.inputs.version || github.ref_name }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install git-changelog
        run: |
          python -m pip install --upgrade pip
          pip install git-changelog

      - name: Generate changelog
        run: |
          CURRENT_TAG="${{ github.event.inputs.version || github.ref_name }}"
          PREVIOUS_TAG=$(git tag --sort=creatordate | grep -B9999 "$CURRENT_TAG" | head -n 1 || true)
          
          if [ -z "$PREVIOUS_TAG" ] || [ "$PREVIOUS_TAG" = "$CURRENT_TAG" ]; then
            echo "No previous tag found. Using initial commit."
            FROM_COMMIT=$(git rev-list --max-parents=0 HEAD)
            git-changelog -F "$FROM_COMMIT..$CURRENT_TAG" --template keepachangelog > TEMP_VERSION_CHANGELOG.md
          else
            echo "Generating changelog from $PREVIOUS_TAG to $CURRENT_TAG"
            git-changelog -F "$PREVIOUS_TAG..$CURRENT_TAG" --template keepachangelog > TEMP_VERSION_CHANGELOG.md
          fi
          
          git-changelog --template keepachangelog > TEMP_CHANGELOG.md

      - name: Switch to main and commit CHANGELOG.md
        run: |
          git fetch origin main
          git checkout main
          mv TEMP_CHANGELOG.md CHANGELOG.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ github.event.inputs.version || github.ref_name }}" || echo "No changes to commit"
          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          body_path: TEMP_VERSION_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}