name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: "Full version tag to create release for (e.g. 'v1.2.3')"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out the repository at the tag
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ github.event.inputs.version || github.ref_name }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install git-changelog
        run: |
          python -m pip install --upgrade pip
          pip install git-changelog

      - name: Generate changelog
        run: git-changelog --template keepachangelog > CHANGELOG.md

      - name: Switch to main and commit CHANGELOG.md
        run: |
          git fetch origin main
          git checkout main
          cp CHANGELOG.md CHANGELOG.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ github.event.inputs.version || github.ref_name }}" || echo "No changes to commit"
          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}